name: renovate

on:
  schedule:
    - cron: "@daily"
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: ghcr.io/renovatebot/renovate:37.279.3
    steps:
      - uses: actions/checkout@v4
      - run: renovate
        env:
          RENOVATE_CONFIG_FILE: "/workspace/elbandi/renovate-config/config.js"
          LOG_LEVEL: "debug"
          RENOVATE_CONFIG_MIGRATION: "true" # ensure all repositories receive config migration PRs
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}

