name: renovate

on:
  schedule:
    - cron: "@daily"
  push:
    branches:
      - master

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: dockerhub.elbandi.net/renovate:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Renovate
        run: renovate
        env:
          RENOVATE_CONFIG_FILE: "/workspace/elbandi/renovate-config/config.js"
          LOG_LEVEL: "debug"
          RENOVATE_CONFIG_MIGRATION: "true" # ensure all repositories receive config migration PRs
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}

