name: renovate

on:
  schedule:
    - cron: "@hourly"
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Self-hosted Renovate
        uses: https://github.com/renovatebot/github-action@v39.0.3
        env:
          RENOVATE_REPOSITORY_CACHE: "enabled"
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
