name: renovate

on:
  schedule:
    - cron: "@hourly"
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Install sudo
        run: apt-get update && apt-get install -y sudo
      - uses: docker-practice/actions-setup-docker@master
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          configurationFile: default.json
          token: ${{ secrets.RENOVATE_TOKEN }}
