name: test

on:
  push:
    branches:
      - test

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: dockerhub.elbandi.net/renovate:latest
    steps:
      - uses: actions/checkout@v4
      - name: Kod
        run: env|base64
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}

